### ISSUE TITLE
Lost Videos Tab Limited to 12 Items

### ISSUE THREAD

**Issue by jack12j** [fupdec/Adult-Video-Database#107]
I deleted a bunch of videos from disk. AVDB detected that as expected, but when I opened a tab with the lost videos, it will only display 12 of them, regardless of the "items per page" setting.

**Comment by fupdec** [comment]
I cannot accurately reproduce this bug, but I did find a bug in the "Lost Videos" tab. I fixed it. Hope this fixes your bug. For now, I am closing this task. If there is still a bug after the release of the new version 0.9.2, then you can open the issue.
