### ISSUE TITLE
[Bug] Can't delete "performer tag" under certain conditions

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#11]
If you create a tag and assign it to "performer category", and then you assign this tag to a performer:
it will work fine, and the tag will appear on the performer details, and you will be able to delete it.

But if after assigning the tag to the performer, you remove it from the "performer category", it will stay on the performer details (i have no problem with that), but you won't be able to delete it from the performer details manually, as the tag won't appear in the menu when you edit the performer.

**Comment by fupdec** [comment]
I understand what is meant by tags in a topic. but
it is better to implement it not with tags, but by adding new parameters to items.

I will explain with an example what is the difference. if you want to add a new category of tags for ear size, then for brevity you will make tags named small, medium, large. and if you want to add a lip category in the future, you run into a naming problem. you will have to name the tags with their full names. and in the database you will have a bunch of similar tags "small ears", "medium ears", "large ears", etc.

Parameters more accurately describe the type and in the future it will be possible to make a more precise search by parameters. there will be several types of parameters: array (for several values), boolean (only two values ​​- true or false), string and number.

This is not an easy task that will only be done after I rewrite the filtering for all items. I understand how different preferences users can have and the parameters will provide them with the opportunity to create a base corresponding to their preferences most accurately.

**Comment by fupdec** [comment]
in the new release v0.6.0, a notification has been added if you remove an already assigned category. when you remove a category, this tag is automatically removed from all performers or videos, depending on the category.
