### ISSUE TITLE
[Request] Dynamic update of (the number) in cards'name

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#12]
We discussed about it in private, but it the end i think that the number (showing the number of corresponding videos or performers) in parentheses beside the name on cards of tags, performers, websites, ... should dynamically update themselves at relevant moments:

- When you add a tag to an object (video, performer, ...)
- When you go on a new page
- When you start the app
- When you refresh a page #9 

The button to update it manually in the settings is not user friendly, i thought it had other purposes and didn't dare to use it and wondered why the number always was "0"
Again, no priority with that, but i found it disturbing.

**Comment by fupdec** [comment]
Previously, the video count information next to the item name was dynamically updated every time the page was refreshed. Switching to manual refreshing has reduced the page load time by several times. In addition, with manual updating, the number of videos is stored in the database and this allows you to quickly process this data, for example, to sort by the number of videos. I understand that this feature needs to be improved, but it will be very expensive to update the information each time. If there are more than 10,000 videos in the database, then the update process takes about 5 seconds, which will lead to the application freezing if you update it frequently. but I think I can make a compromise and do an automatic update periodically as the user wishes (once an hour, once every 10 minutes, or when the application starts).

**Comment by mf35** [comment]
Yes i think the most important thing is to let the user have options/choices.
A good quick solution could be to make the update button more explicit and less hidden.

But i'm sure it will be all about compromises.

**Comment by fupdec** [comment]
added autoupdate with user selectable interval in release v0.6.2
