### ISSUE TITLE
[Request] Create custom tag types/categories

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#13]
As the title says and like we discussed it in private, custom tag types would allow anyone to organize videos in a much more flexible way.
So instead of having just "video" and "performer" categories, you could have personnal things like "look attributes", "level of softness/hardcoreness", "censored/not censored", "number of performers", "type of video", ...

With that, i don't know if it will be necessary to constraint "video tags" to videos and "performer tags" to performer.
Maybe just put a "tags" tab, and let users do their own categories and assign the tags wherever they want :)

I know it's more appealing to have prebuilt categories for new users, so you can keep "video tags" and "performer tags" as default tag categories, but then you should create a list of these categories and allow the user to activate, desactivate, delete, rename, manage them. Maybe like playlists.

**Comment by fupdec** [comment]
I understand what is meant by tags in a topic. but it is better to implement it not with tags, but by adding new parameters to items.

I will explain with an example what is the difference. if you want to add a new category of tags for ear size, then for brevity you will make tags named small, medium, large. and if you want to add a lip category in the future, you run into a naming problem. you will have to name the tags with their full names. and in the database you will have a bunch of similar tags "small ears", "medium ears", "large ears", etc.

Parameters more accurately describe the type and in the future it will be possible to make a more precise search by parameters. there will be several types of parameters: array (for several values), boolean (only two values ​​- true or false), string and number.

This is not an easy task that will only be done after I rewrite the filtering for all items. I understand how different preferences users can have and the parameters will provide them with the opportunity to create a base corresponding to their preferences most accurately.

**Comment by fupdec** [comment]
This feature added in release v0.5.8
