### ISSUE TITLE
[Request] Advanced player/playlist controls

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#15]
Small request, and i know that you plan to implement it, but as a reminder:
Adding classic player controls like:
- Shuffle playlist
- Automatic playing (currently playlist playing stop when a video is ending, when it should play the next one)
- Loop

And in the further future, maybe some less classic stuff like:
- Play videos in playlist at random time
- Play them for a chosen duration
- Play videos for a chosen number of time before going to the next one

So you could have your all library shuffled, with videos beginning at random moment for, let's say 10 secondes, before going to the next one playing in the same way.
Like if you had a big gifs collection.

**Comment by fupdec** [comment]
usual modes added in release v0.6.7
