### ISSUE TITLE
Open file (or file location) externally fails

### ISSUE THREAD

**Issue by bstzaa** [fupdec/Adult-Video-Database#155]
**Describe the bug**
Open file (or file location) externally fails

**To Reproduce**
1. Go to Videos
2. Right click on a video to open context menu
3. Click on "Open video in" or "Open file's folder"
4. If the video's path contains a space, this will try to open the path until the space, likely failing to find it. For example, if the path is "D:\src\01 Somestring" it appears to be trying to open "D:\src\01" instead.

**Expected behavior**
File or folder opens

**Screenshots**
![image](https://github.com/user-attachments/assets/28a9831f-1e45-42e1-bafd-65071f8fb10e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - App Version v12 beta from Discord

**Comment by fupdec** [comment]
fixed in v0.12.1
