### ISSUE TITLE
[Bug] Performer informations banner can't close

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#16]
When you click on a performer card, but on the title banner at the bottom, it pops this banner at the bottom of the app: https://imgur.com/4ByADH3

Problem is that you can't close/hide it afterwards, it's a problem when you have the navigation bar at the bottom, you can't access it anymore :)

**Comment by fupdec** [comment]
the banner is temporarily removed until I come up with the best solution for where it could be located.  release v0.5.9
