### ISSUE TITLE
Exception on application start

### ISSUE THREAD

**Issue by lesha-dev** [fupdec/Adult-Video-Database#160]
**Describe the bug**

Installed application for the first time.
Launched application. Got error:

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: EPERM: operation not permitted, open 'C:\Program Files\MediaChips\resources\app\dist\config.json'

After closing popup nothing happens.

**To Reproduce**
1. Install MediaChips
2. Run MediaChips from Start Menu
3. See error message

**Expected behavior**
The application starts.

**Screenshots**
![2024-11-23_15-06-30](https://github.com/user-attachments/assets/8500c7e1-f634-4e31-b53e-c9d12acd05b7)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - App Version: MediaChips.v0.12.0.Windows.Installer

**Additional context**

**Comment by fupdec** [comment]
this is because the application runs without administrator rights

**Comment by lesha-dev** [comment]
Thank you! That solves the issue.

**Comment by fupdec** [comment]
will be fixed in the next release
