### ISSUE TITLE
[Bug] Add to favorite button not really working

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#17]
In performers page, when the option "View" > "Rating and Favorite in Cards" is checked, and when you click the "heart" favorite button below the name of the performer; the button is reacting (heart turns on or off) but the change is not saved (when you leave the page and come back, it's like you've never done anything).

This problem seems to only concern the performers page and not the videos page.

**Comment by fupdec** [comment]
Fixed in release v0.5.9
