### ISSUE TITLE
 preserve image quality

### ISSUE THREAD

**Issue by kronometroz** [fupdec/Adult-Video-Database#2]
some way to preserve image quality on performers, on large screens it gets very distorted.

thanks

**Comment by fupdec** [comment]
thanks for using my app. what screen resolution are you using? on my computer I use 1920 x 1080 and even in XL card size the performer images look good. I cannot test the higher resolution, as I only have a full hd monitor. I use performer image compression to improve performance and save space. I'll check the performance without compressing images. if this does not affect performance, then perhaps I will make a setting for choosing the quality of pictures or leave it uncompressed by default. but most likely you are using a low quality source pictures.

**Comment by fupdec** [comment]
have you tried using high quality image sources?

**Comment by fupdec** [comment]
in the 0.5.4 release I increased the quality of the pictures. сheck, please.

**Comment by kronometroz** [comment]
its ok , thanks
