### ISSUE TITLE
Save sorting on Tags page

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#20]
I saw that you fixed #6  the sorting options not saving on exit, but i was hoping this fix especially for the Tags page, because i sort my Tags by colors (like if colors were categories).

So i propose that you could extend this to the Tags page, but also to the Websites and Playlists pages.

**Comment by fupdec** [comment]
Yes, you are right - now only performers and videos saves after exit. Problem with save other states which needs to be recreated with new filters like on page with videos. Thank you for let me know about this. I thought this is not necessary.

**Comment by mf35** [comment]
No problem. I'm using a lot the tags page, so i guess i can't be the only one :)

**Comment by fupdec** [comment]
fixed in release v0.6.2
