### ISSUE TITLE
More tags categories

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#21]
As a personal suggestion, i would love to see more categories for tags.
They don't have to be necessarily dynamic or smart, but they could be used to "categorise" tags literally.

The goal would be to separate tags in different sections visually.
I have 85 tags so it could be more efficient if they were separated.

I can see two ways to achieve this.

1. Currently i use a workaround with colors, and use them like separated "groups" of tags.
Maybe give the possibility to assign a custom name to each color, so when you sort your tags by colors #20 , you can see them grouped and separated, with the name of the group as header.

2. Give the possibility to add new custom tag categories, like "video" and "performer".
The custom tag categories would be used for sorting only, and won't be specially linked to videos or performers.
And then we could sort tags by categories like in point 1.

**Comment by fupdec** [comment]
I think better is the 2 variant. I will move video and performer into a different datatype.  perhaps it will be called the "tag type" or something else.  for now, a temporary solution for you is to add a synonym or alias to your tags.

**Comment by mf35** [comment]
It's really "visual", so alias won't really change the thing for me i guess.
I was thinking of something looking like this in the end:

![Tags categories](https://user-images.githubusercontent.com/78038212/108282428-e3b5e280-7181-11eb-9a7a-f5d9cbea8e25.jpg)

**Comment by mf35** [comment]
Maybe with a separation line like <hr> between categories.

**Comment by fupdec** [comment]
Looks accurate. I will take this into account in the future.

**Comment by fupdec** [comment]
I think we can use this idea for separate other types of cards by chosen type like colour, first letter, category and etc. But it will be hard to implement with pagination. This feature will be added after beta release.

**Comment by mf35** [comment]
> 
> 
> I think we can use this idea for separate other types of cards by chosen type like colour, first letter, category and etc. But it will be hard to implement with pagination. This feature will be added after beta release.

Yes indeed, i didn't think about pagination.
Maybe i'll come up with something different, after using the app for some times.

**Comment by fupdec** [comment]
in the distant future, maybe I will add an infinite loading of items, then the pagination problem will not be important.

**Comment by mf35** [comment]
Ok, but i think you should let the user choose between the two anyway.
Infinite scrolling can be problematic if you have a ton of videos, even filtered.

**Comment by fupdec** [comment]
tag categories added in release v0.6.6. i opened new issue #25 for separator.
