### ISSUE TITLE
Filtering by tags on click

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#22]
When you click on a performer card on the performers page, you can see all the videos with this performer in it.
I would love to see this functionnality back for the tags page, so when you click on a tag, you can see all the videos using that tag directly and quickly.

**Comment by fupdec** [comment]
Tag page was removed because too many resources were required to create two types of tabs: video and performers.  In the future, there will be something like a quick filter by tag, if you click on it. there will also be a quick filter for the tag that is assigned to the video and performer.

**Comment by mf35** [comment]
Yes i was thinking more about a "quick filter" :)

**Comment by fupdec** [comment]
added with any other filters in version v0.6.3. check release page for more details about filters.
