### ISSUE TITLE
Multiple Nationalities

### ISSUE THREAD

**Issue by fupdec** [fupdec/Adult-Video-Database#24]
due to the fact that I decided to abandon selects in which only one value is allowed, I want to provide the ability for users to select one or more values themselves. previously only one website could be selected.

**Comment by mf35** [comment]
i'm sorry if it's off topic, but is it in connection with what you have planned for "parents" and "children" websites relation ?

**Comment by fupdec** [comment]
no, this only applies to performers.

**Comment by fupdec** [comment]
added in release v0.6.6
