### ISSUE TITLE
Renaming tags can break markers

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#26]
Alright, i found and isolated an interresting bug.

Put a tag marker on a video, then rename this tag on the tags page.
This renaming won't be echoed in the markers database file (dbm.json), resulting in breaking several things when you play this video:

- Timeline won't respond and markers won't appear on it.
- You won't be able to open sided videos list or markers list.
- You won't be able to manage new markers.

Renaming the tag in dbm.json file accordingly resolved the problem.

**Comment by fupdec** [comment]
I didn't try to reproduce it but I think problem with updating tags state in player. If add a new tag it will don't appear in player's tags. Need to updating player tags. Temporary solution maybe rerun app after any manipulation with tag name.

**Comment by mf35** [comment]
I don't know if i got understood, let me explain with a clearer example:

- I create a tag named "Beauty" in the tags page.
- I go to videos page and launch the video "A".
- In the video player, i create a "tag" marker and i choose the "Beauty" tag.
- I close the app, or do something else.
- I come back to the tags page and i edit the "Beauty" tag's name and change it to "Beautiful"
- I launch the video "A", and the problems described in my previous post happen, because in the dbm.json, the tag's name is still "Beauty" and not "Beautiful".

**Comment by fupdec** [comment]
After you added tag, renamed or deleted just rerun app. For better understanding how tags connects with player. On start app main window send a copy of object with tags to player window. One time. But it should be every time after tag object changed.

**Comment by mf35** [comment]
Ok, right now i have already some tags set.
So i just launched a video, added an existing marker tag to it on its timeline, everything's ok.
Then i went to tags page, renamed the tag i just used, and relaunched the video. Everything was working, except that the tag's name has not changed on the marker's video (on the timeline and on the markers'list)

So i closed the app and opened it again.
And when i re-launched the video, it was worse, like i described it in the first post, no more markers on timeline, can't open playlist and markers list.
Then i checked dbm.json file, the tag's name was not changed there, and **the problem is solved only when i change the tag's name there**.
I'm talking about **dbm.json**, so the markers related file, not the tags related file.

**Comment by mf35** [comment]
It's really easy to reproduce, you should try the step by step i gave. :)

**Comment by fupdec** [comment]
I understand, when you renamed any tag its name don't updating in markers database. It's a mistake, it should be fixed.

**Comment by mf35** [comment]
Yes that's it :)

**Comment by fupdec** [comment]
Fixed in release v0.7.1
