### ISSUE TITLE
[Bug] Multi-Editing Issues

### ISSUE THREAD

**Issue by DarkMask100** [fupdec/Adult-Video-Database#31]
I've noticed when adding tags/updating performers on multiple videos, it seems to add these changes to every video.

**Comment by fupdec** [comment]
It's not a bug. This works how it should be. If you selected multiple videos and than you will open edit dialog from context menu the dialog will be different by the dialog with a single video.

**Comment by DarkMask100** [comment]
Ah I should of explained it a bit better. 

If I select video 1 & 2 it will select both videos. However if I click away and select video 3 & 4, it will also select video 1& 2. I have to change sections for the selector to reset properly.

**Comment by mf35** [comment]
Oh yes indeed, the video cards selection is not working well.
You should open an issue for this specific problem.
First selections, most of the time, are working as intended (with "ctrl" or "shift" keys combinaison), but then it keeps selecting more video cards in a wierd way.

Hard to explain, but anyway, cards selection has some flaws.
