### ISSUE TITLE
[Bug] Error when login with a password

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#4]
When a password is set and i log in the app, if i validate my password with keyboard (_enter_ or _return_ key), i get an error.

![error](https://user-images.githubusercontent.com/78038212/105879405-6bd11e00-6002-11eb-8eb1-fc2bf7c76b1b.jpg)

I can dismiss error and write password again, but nothing happens if i validate with keyboard again.
This bug doesn't happen when i click on "Log in" button to validate.

**Comment by fupdec** [comment]
Fixed in a new version 0.5.7
