### ISSUE TITLE
Save Zoom on exit

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#43]
Hello, small request here.
Is it possible to save the "View > Zoom" option after app is closed ?

Thank you :)

**Comment by fupdec** [comment]
Yes, It will be fixed.

**Comment by mf35** [comment]
Hello sorry, but it seems that only the View > Zoom option slider position is saved.
The Zoom itself is not applied when i restart the app.

Can you reproduce it ?

**Comment by fupdec** [comment]
I checked you are right. will be fixed for next release. Feel free to open the issue if they are already closed.
