### ISSUE TITLE
[Issue/Request] HEVC Support

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#5]
I don't know if it has to go in "issues" or "request"category but for me it's my biggest issue. :(
The player is not able to play or create animated preview of videos made of H.265/HEVC codec.
I have audio but video is black.

3x3 grid preview though is working on those HEVC encoded videos.

**Comment by fupdec** [comment]
Videos with H.265/HEVC codec now supported by new embedded player which based on VLC player. In release v0.5.8
