### ISSUE TITLE
[Request] Save sorting options after exit

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#6]
I propose that, like the filtering options, all sorting options would be saved after exiting the app.
I'm talking about options like "Show favorites", "Sort by ...", ...

When you open a video in a new page: you have a "Show names" button for the markers on the right which is not remembered either, just by leaving the page.
I think all the states for those kind of options should be saved anytime :)

Thank you.

**Comment by mf35** [comment]
So i also found that option in View > Rating and Favorite in Cards
is not saved after exiting app.

**Comment by mf35** [comment]
Also this, in my original post: 
"_When you open a video in a new page: you have a "Show names" button for the markers on the right which is not remembered either, just by leaving the page._"

...is irrelevant now. I think you just wanna make sure that all the ui customisation and sorting options are saved after exiting :)

**Comment by fupdec** [comment]
Fixed in release v0.6.1
