### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Sliceofair** [fupdec/Adult-Video-Database#68]
It is stuck on splash screen. I have tried latest portable and installer versions for windows.

**Comment by mf35** [comment]
Are you on Windows ?
It happens to me rarely, like a Windows process problem.
I have to use task manager and close all avdb process, then it's good again.

**Comment by Sliceofair** [comment]
Windows 10. Closing process or restarting PC doesn't help, never goes past splash screen.

**Comment by fupdec** [comment]
Do you see the square AVDB logo and it doesn't disappear?
at what stage do you get stuck?
have you tried running as administrator?

**Comment by Sliceofair** [comment]
Yes it is the square pink-black logo, on taskbar it says "loading". Running as admin makes no difference.

**Comment by fupdec** [comment]
It is difficult to do any debugging at this stage. I have not encountered similar problems before.
If you see a square, then you can open the debug console. To do this, press the KTRL + SHIFT + I buttons. Then go to the console tab and see if there is any text highlighted in red. If so, attach it to the message.
I can suspect that you have some application running that runs a local server and is using the same port as my application. The port may be blocked by a firewall. You can try to disable all antiviruses while the application is running.
You can also try to create a new user, giving him maximum rights.

**Comment by fupdec** [comment]
Also, if possible, I would like to see exactly what tasks related to the application you are running. I do not need extraneous applications, I just need the AVDB application. Usually it has about five subtasks combined into one.

**Comment by Sliceofair** [comment]
Task manager screen snip: [https://ibb.co/CJ6k807](https://ibb.co/CJ6k807)

ctrl+shift+I didn't work on splash screen.

It turns out Windows Defender blocks it from running. It doesn't give any warnings, if I scan your app it finds no threats, but having real time protection ON prevents your app from starting. Afer I have added the exe to exclusions it is working now.

**Comment by Sliceofair** [comment]
Exclusion list works only for the installed app, the portable version won't work even after adding entire folder containing the app to the exclusion list.

On another note this is probably unrelated but most videos do not work for me with build-in player, I only get sound and black screen.

**Comment by fupdec** [comment]
> On another note this is probably unrelated but most videos do not work for me with build-in player, I only get sound and black screen.
So far, only those formats are supported that are supported by the Chrome browser itself. There is extensive work to be done on this. #42
