### ISSUE TITLE
[Request] Markers management like playlist

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#8]
When you open a video in windowed mode, you have a button to open a nice playlist on the right side of the video.
I propose that the button dedicated to markers will open the same kind of list but with markers.

So you can jump to specific parts of the video according to the kind of marker you added:
- Favorite moments. (favorite marker)
- Specific actions. (tag marker)
- Specific performer. (performer marker) #10 
- Free text note (bookmark marker)

Not only it's more convenient to use them this way but it's also more convenient when you have to create them.

About this list's look, each marker should be displayed as a thumbnail of the video frame it was assigned to.
You could display the name and the icon of the marker:
- Tag icon + Name of the tag. (for tag markers)
- Heart icon (for favorites)
- Bookmark icon (for bookmarks)
- Performer icon + Name of the performer (for performer markers)

You could even implement your colored corner system if the user use it.

**Comment by fupdec** [comment]
Added in release v0.5.8
