### ISSUE TITLE
Add a ratings option to the meta options

### ISSUE THREAD

**Issue by draftvader** [fupdec/Adult-Video-Database#87]
I know we can set an array with numbers but this does not translate visually. It would be nice to be able to rate our performers based on their "assets" in a fun, visual, manner. This is such a subjective subject but some scenes have great action but less than stunning performers (still happy to watch). Sometimes, however, I want to watch a forgotten scene with a type of action and a certain "level" of quality from a particular asset....if you get what I mean ;)

**Comment by fupdec** [comment]
Feature added, will appear in release 0.9.2
