### ISSUE TITLE
[Request] Customizable shortcuts

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#9]
Not a priority imho, but in the future, settings for keyboard and mouse shortcuts customization could be very helpful.
Some examples:

• toggling playlist
• toggling markers list #8
• jumping to next or previous marker
• playing next or previous video in the playlist
• toggling full screen video mode
• cards selection (with Ctrl or Shift click combination; or Ctrl+a to select all)
• adding a marker
• adding a tag
• refresh a page (F5) #12

**Comment by fupdec** [comment]
added in release v0.6.7. 
also added mouse shortcuts for mouse side buttons (back and forward buttons):
- on the screen it is previous/next video
- on the timeline it is previous/next marker
