### ISSUE TITLE
"Parse Metadata" (right click option) is assigning a "default" website

### ISSUE THREAD

**Issue by draftvader** [fupdec/Adult-Video-Database#92]
I haven't yet observed this with the parsing through the main import function. When I highlight a video in "Videos", right click then choose "parse metadata" it is attributing the scraped info but also adding another website (if it helps I believe this site might have been my default site).

I have tried to rename the offending website by taking out the whitespaces and I have removed all alternate website names. This problem still persists.

Last point. I don't remember this happening when I was first adding performers and videos. It seems like it only started in the past few days. Don't quote me on this!

**Comment by draftvader** [comment]
User error. I found an alternate name. Not sure why I missed it. Please ignore.

**Comment by fupdec** [comment]
Can I close this issue?

**Comment by draftvader** [comment]
Please close. Thank you
